project:
  type: website

website:
  title: "Jules974"
  description: "This is Julien Delmas's personal Blog"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/murgen974

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

